server:
  port: 80




spring:
  application:
    name: order-consumer-openfeign

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848


feign:
  client:
    config:
      default:
        connect-timeout: 1000
        read-timeout: 2000
  sentinel:
    enabled: true
